### PR TITLE
moss: Run nixfmt

### PR DESCRIPTION
**Pull request by albertchae**
nixpkgs typically requires that nix files have `nixfmt` run on them, so we want to merge a separate structural PR that does this before making semantic changes in https://github.com/openXC7/toolchain-nix/pull/4 (we will rebase that PR after this one is merged to get it into a mergeable state).

### CODE REVIEW

**Comment by albertchae** [comment]
@hansfbaier if you're not opposed to running `nixfmt` on this codebase, could we merge this PR to unblock rebasing https://github.com/openXC7/toolchain-nix/pull/4 ?

**Comment by hansfbaier** [comment]
Yes no problem

**Comment by albertchae** [comment]
Great, can you do the merge @hansfbaier ? I don't think anyone in the moss mob has permissions

**Comment by hansfbaier** [comment]
@albertchae merged, many thanks!

**Pull request merged**
